### ISSUE TITLE
Langswitcher do not works with Gravi-k theme

### ISSUE THREAD

**Issue by garduino** [Edelan/grav-theme-gravi-k#1]
I'm newbie with GRAV and trying to do my first website with it. I need it in English and Spanish and I like the Gravi-k theme, but I can't find the way to make both work together.
I read all that I found, tried to include the Twig partials on the theme (in different places, as l read experiences with other themes), but nothing seems to work.
With the default theme it works ok.

**Comment by Edelan** [comment]
Hello, I understand what you want, I'll look at this problem, I inform you as soon as possible.

**Comment by garduino** [comment]
Thanks you Eric, let me know if I can collaborate with testing for example.
Cheers.

**Comment by Edelan** [comment]
Hi, I tested the plugin and it works for me, have you clear the cache?

**Comment by garduino** [comment]
Yes, I tried all the stuff that I figured out, as I commented above.

I never saw the links for switch languages in the front page, neither in other pages of the site.

**Comment by Edelan** [comment]
Ok, where are you put the partial templates langswitcher, in the navbar menu?

**Comment by garduino** [comment]
I tried in several places, but none seems to work (for example /user/themes/gravi-k/templates/partials and then in base.html.twig.

But it's very possible that I do now know how to enable langswitch in Gravi-k. If you can point me some steps to test here I can do it.

Thanks.

**Comment by Edelan** [comment]
It is possible to do something like that, include the template langswitcher in the template menu, for give that:
![prtscr capture_4](https://cloud.githubusercontent.com/assets/12407621/16351064/cadb2710-3a5a-11e6-92f7-70dc78194632.jpg)

Find the template menu in partials folder, copy and paste by replacing the nav block or just new lines

```
<div class="nav">
  <nav class="nav-links" role="navigation">
    {% include 'partials/navigation.html.twig' %}

    {% if config.plugins.langswitcher.enabled %}
    <span class="nav-spacer"></span>
    {% include 'partials/langswitcher.html.twig' %}
    {% endif %}

  </nav> 
</div>
```

and then add a custom css like that

```
.nav-links ul { display: inline;}
.langswitcher { margin-top: 0;}
.langswitcher li { margin-left: 0; line-height: 1.5;}
.langswitcher a { padding-left: 5px; padding-right: 5px; text-transform: capitalize;}

@media screen and (max-width: 768px) {
 .langswitcher:before { content: 'lang:'; font-family: inherit; text-transform: capitalize; } }
 .nav-spacer { display: inline-block; width: 2px; height: 11px; background-color: $color-theme; }
```

replace $color-theme with the color of your choice.

Then it's important to have modular folders with versions of each language

like that:

home
-- home.en.md
-- home.es.md
-- / features
-- / --features.en.md
-- / --features.es.md
etc...

I hope it will work.

Regards.

**Comment by garduino** [comment]
Hi!

Thanks you! Seems to work now.

My remaining doubt is that if the custom css must be a file called custom.css in the css folder of the site or a _custom.css file in the scss/gravi-k folder of the theme or any other option...?

I'm having a little problem (may be related with the css) that the language links are not at the right of the logo, else in another line, as in the attached pic. How I can make them fit in the same line than the main menu? 

![pic](https://cloud.githubusercontent.com/assets/1567982/16357709/78e0519a-3ad4-11e6-9316-26f407aa669e.png)

Thanks again for your help!

**Comment by Edelan** [comment]
Hi, for that forget my previous comment, you must change the position of the `template langswitcher` in between the div menu-logo and the div nav, and add css inline like that

```
<div class="menu-logo">
.... 
</div>    
  {% if config.plugins.langswitcher.enabled %}
    {% include 'partials/langswitcher.html.twig' %}
  {% endif %}     
 <div class="nav">
....
</div>
 <style>
.langswitcher {
-webkit-transform: translateY(-25%);
-moz-transform: translateY(-25%);
-o-transform: translateY(-25%);
-ms-transform: translateY(-25%);
transform: translateY(-25%);
}

@media screen and (max-width: 768px) {
.langswitcher {
  -webkit-transform: translateY(0%);
  -moz-transform: translateY(0%);
  -o-transform: translateY(0%);
  -ms-transform: translateY(0%);
  transform: translateY(0%);
  }
}
</style> 
```

You can adjust the value (25%) of `translateY` if the vertical-align isn't in middle.

Regards.

**Comment by garduino** [comment]
It works perfectly now! Thanks you very much for your help!!!
