### ISSUE TITLE
Disable the color picker

### ISSUE THREAD

**Issue by derbu** [Edelan/grav-theme-gravi-k#14]
Hi Eric,

your template is really great!

Is it possible to disable the color picker on the top right site, but nevertheless choose a color in the template settings?

Thanks a lot
Regards
Sebastian

**Comment by Edelan** [comment]
Hi Sebastian,

I changed the theme configuration to disable the color picker and let the choice of a color among the 8 possible.

thanks for comment.
Regards
Eric
