### ISSUE TITLE
Footer settings

### ISSUE THREAD

**Issue by derbu** [Edelan/grav-theme-gravi-k#15]
Hi Eric,

me again.

Is there another way to change the copyright year in the footer instead of editing it manually?
user/themes/gravi-k/templates/partials/footer.html.twig:
`<span>&#169; 2016 {{theme_config.contact.name}} | All Rights Reserved</span>`

Maybe it is possible to use a date variable here?

Thanks & regards
Sebastian

**Comment by derbu** [comment]
I've opened a pull request for it

**Comment by Edelan** [comment]
Hi Sebastian,

I do not know what happened with the merge, but your request was included in the template. Thanks for that.

Regards.
Eric.
