### ISSUE TITLE
custom.css

### ISSUE THREAD

**Issue by OptikWebCreative** [Edelan/grav-theme-gravi-k#2]
Hi Eric,  

Great Template, but Im having problems with CSS mods, I've created /css/custom.css but the template doesn't seem to be accepting it?

Caches have been cleared

Any Thoughts?

**Comment by Edelan** [comment]
Hello Rich,

Have you added  `{% do assets.addCss('theme://css/custom.css') %}` to the template head.html.twig located in the the partials folder. This add must be in the block stylesheet.

Regards.
