### ISSUE TITLE
gravi-k slider and FAQ sliding effects do not work here

### ISSUE THREAD

**Issue by nickbe** [Edelan/grav-theme-gravi-k#3]
Just installed the latest GRAV beta.
But this is all I get - no slider.

![screenshot_48](https://cloud.githubusercontent.com/assets/10890765/16481668/b71375ec-3eac-11e6-9ebe-b324337c46c8.png)

**Comment by Edelan** [comment]
Hi,
Do you have installed the plugin LightSlider?
Two plugins are required LightSlider for the slider and Featherlight for the image gallery.

thanks for testing my template.
Regards.

**Comment by nickbe** [comment]
Ah those were not mentioned on the github site. At least I didn't see them there. 
Thanks!
