### ISSUE TITLE
google map not working on centos7/httpd

### ISSUE THREAD

**Issue by k1ngf15h3r** [Edelan/grav-theme-gravi-k#4]
It is not a theme issue but maybe you can help me with my issue

your theme works correct with apache2 on my kali linux. when I push the site to my root server running cent os 7 and httpd I got an error with javascript with the google map.

tried to change script type to `application/javascript` in the google-map.html.twig and also tried with adding `AddType text/javascript .js` in my httpd.conf but it does not render the map

any ideas how to fix this?

**Comment by Edelan** [comment]
Hi, thanks for testing my template, but sorry i have no idea for this problem.
Good luck.
