### ISSUE TITLE
Problem compiling scss files

### ISSUE THREAD

**Issue by nickbe** [Edelan/grav-theme-gravi-k#7]
I have no idea how to compile your scss files. 
Could you please provide the current sass command for us?

Thanks

**Comment by Edelan** [comment]
Hi, sorry for the late reply

for compiling scss files i have:

1- a main.scss , in the scss folder, with the @import files like that:

<pre>
@charset "UTF-8";
@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700);
@import url(https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700,300);
@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600,400italic,700,300);
@import url(https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700);
@import url(https://fonts.googleapis.com/css?family=Montserrat:400,700);
// General settings
@import "knacss/01-variables";
@import "knacss/mixins";
@import "knacss/02-config";
// components
@import "knacss/components";
</pre>

2- then i work with gulp and sass tasks for compiling.

Regards.

**Comment by nickbe** [comment]
Thanks. 
I suspected there was a main file missing. Please make sure that you deliver all necessarx files in your theme. Otherwise users will have a hard time adapting your theme (we had).

Also I siggest when including the css files you always check wether a min version is present and fall back to include a normal css file instead.

**Comment by Edelan** [comment]
ok, it was my first commit for the next time I will do as you say.
Thanks.

**Comment by nickbe** [comment]
Great. And btw. I'm already using your theme. Absolutely georgous.
A big thanks for the effort you'd put into this.
Really great work!

**Comment by kmcital** [comment]
Agree 100%, beautiful theme but we wasted a lot of time trying to customize since scss setup was incomplete. Check out Deliver theme which has a very well organized set of scss files and even provides the scss.sh to watch for changes. It may give you a few ideas. Otherwise excellent work!

**Comment by Edelan** [comment]
Sorry for the late, i don't know if this issue need a response yet.

**Comment by nickbe** [comment]
Don't worry. This was just meant as a hint for you. Finding out how to make Scss compiling work is as much a thing to learn for us ;) 

So simply thanks again for the beautiful theme :D

**Comment by mathewmeconry** [comment]
Hey @Edelan 

I know this issue is really old, but there is still no main.scss file...
By the way, is this repo/theme still supported?
