### ISSUE TITLE
Template Error after update

### ISSUE THREAD

**Issue by fiddler1** [Edelan/grav-theme-gravi-k#9]
Template Gravi-K.
 I'm getting the following error after upgrading grav and plugins.

Getting error.
Whoops \ Exception \ ErrorException (E_NOTICE)
Undefined index: fields
// Fix naming for fields (presently only for toplevel fields)
foreach ($this->items['fields'] as $key => $field) {
// default to text if not set
if (!isset($field['type'])) {
$field['type'] = 'text';}

Installed previous version of FORM 1.3.2 and all is working.

**Comment by fiddler1** [comment]
Hi 
The updated FORM Plugin is causing the Error. 
If I remove templates Pages and substitute Antimatter Pages all is OK?

**Comment by Edelan** [comment]
Hi, 
i fixed this bug, and committed the change. You can download the modified files.
Can you tell me if it works.
Thanks for testing my template.

**Comment by fiddler1** [comment]
Hi Eric
All is working perfectly after you modified the files.
Thanks
